[32m[I 2023-01-17 00:12:40,502][0m A new study created in memory with name: no-name-38657fe7-cce5-4f4f-9ab0-d28f4557e0fa[0m
[33m[W 2023-01-17 00:12:41,245][0m Trial 0 failed because of the following error: ValueError('y contains previously unseen labels: [2]')[0m
Traceback (most recent call last):
  File "/Users/kevinmaikjablonka/miniconda3/envs/gptchem/lib/python3.9/site-packages/optuna/study/_optimize.py", line 196, in _run_trial
    value_or_values = func(trial)
  File "/Users/kevinmaikjablonka/git/kjappelbaum/gptchem/src/gptchem/models/xgboost.py", line 83, in <lambda>
    lambda trial: objective(
  File "/Users/kevinmaikjablonka/git/kjappelbaum/gptchem/src/gptchem/models/xgboost.py", line 68, in objective
    model.fit(
  File "/Users/kevinmaikjablonka/miniconda3/envs/gptchem/lib/python3.9/site-packages/xgboost/sklearn.py", line 522, in fit
    evals = list(
  File "/Users/kevinmaikjablonka/miniconda3/envs/gptchem/lib/python3.9/site-packages/xgboost/sklearn.py", line 523, in <genexpr>
    DMatrix(eval_set[i][0], label=self._le.transform(eval_set[i][1]),
  File "/Users/kevinmaikjablonka/miniconda3/envs/gptchem/lib/python3.9/site-packages/sklearn/utils/_set_output.py", line 142, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
  File "/Users/kevinmaikjablonka/miniconda3/envs/gptchem/lib/python3.9/site-packages/sklearn/preprocessing/_label.py", line 139, in transform
    return _encode(y, uniques=self.classes_)
  File "/Users/kevinmaikjablonka/miniconda3/envs/gptchem/lib/python3.9/site-packages/sklearn/utils/_encode.py", line 231, in _encode
    raise ValueError(f"y contains previously unseen labels: {str(diff)}")
ValueError: y contains previously unseen labels: [2]
Traceback (most recent call last):
  File "/Users/kevinmaikjablonka/git/kjappelbaum/gptchem/experiments/03_classification/henry/run_experiments.py", line 78, in <module>
    run_experiment(train_size, num_class, target, i + 223342)
  File "/Users/kevinmaikjablonka/git/kjappelbaum/gptchem/experiments/03_classification/henry/run_experiments.py", line 43, in run_experiment
    baseline_res = train_test_henry_classification_baseline(
  File "/Users/kevinmaikjablonka/git/kjappelbaum/gptchem/src/gptchem/baselines/henry.py", line 373, in train_test_henry_classification_baseline
    baseline.tune(X_train.values, y_train_binned.values)
  File "/Users/kevinmaikjablonka/git/kjappelbaum/gptchem/src/gptchem/models/xgboost.py", line 82, in tune
    study.optimize(
  File "/Users/kevinmaikjablonka/miniconda3/envs/gptchem/lib/python3.9/site-packages/optuna/study/study.py", line 419, in optimize
    _optimize(
  File "/Users/kevinmaikjablonka/miniconda3/envs/gptchem/lib/python3.9/site-packages/optuna/study/_optimize.py", line 66, in _optimize
    _optimize_sequential(
  File "/Users/kevinmaikjablonka/miniconda3/envs/gptchem/lib/python3.9/site-packages/optuna/study/_optimize.py", line 160, in _optimize_sequential
    frozen_trial = _run_trial(study, func, catch)
  File "/Users/kevinmaikjablonka/miniconda3/envs/gptchem/lib/python3.9/site-packages/optuna/study/_optimize.py", line 234, in _run_trial
    raise func_err
  File "/Users/kevinmaikjablonka/miniconda3/envs/gptchem/lib/python3.9/site-packages/optuna/study/_optimize.py", line 196, in _run_trial
    value_or_values = func(trial)
  File "/Users/kevinmaikjablonka/git/kjappelbaum/gptchem/src/gptchem/models/xgboost.py", line 83, in <lambda>
    lambda trial: objective(
  File "/Users/kevinmaikjablonka/git/kjappelbaum/gptchem/src/gptchem/models/xgboost.py", line 68, in objective
    model.fit(
  File "/Users/kevinmaikjablonka/miniconda3/envs/gptchem/lib/python3.9/site-packages/xgboost/sklearn.py", line 522, in fit
    evals = list(
  File "/Users/kevinmaikjablonka/miniconda3/envs/gptchem/lib/python3.9/site-packages/xgboost/sklearn.py", line 523, in <genexpr>
    DMatrix(eval_set[i][0], label=self._le.transform(eval_set[i][1]),
  File "/Users/kevinmaikjablonka/miniconda3/envs/gptchem/lib/python3.9/site-packages/sklearn/utils/_set_output.py", line 142, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
  File "/Users/kevinmaikjablonka/miniconda3/envs/gptchem/lib/python3.9/site-packages/sklearn/preprocessing/_label.py", line 139, in transform
    return _encode(y, uniques=self.classes_)
  File "/Users/kevinmaikjablonka/miniconda3/envs/gptchem/lib/python3.9/site-packages/sklearn/utils/_encode.py", line 231, in _encode
    raise ValueError(f"y contains previously unseen labels: {str(diff)}")
ValueError: y contains previously unseen labels: [2]
